//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
//*************************DO NOT MODIFY**************************
export var App;
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Ads
     */
    var Ads = (function () {
        function Ads() {
            //nothing                   
        }
        return Ads;
    }());
    App.Ads = Ads;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetRoleClaims
     */
    var AspNetRoleClaims = (function () {
        function AspNetRoleClaims() {
            //nothing                   
        }
        return AspNetRoleClaims;
    }());
    App.AspNetRoleClaims = AspNetRoleClaims;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetRoles
     */
    var AspNetRoles = (function () {
        function AspNetRoles() {
            //nothing                   
        }
        return AspNetRoles;
    }());
    App.AspNetRoles = AspNetRoles;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetUserClaims
     */
    var AspNetUserClaims = (function () {
        function AspNetUserClaims() {
            //nothing                   
        }
        return AspNetUserClaims;
    }());
    App.AspNetUserClaims = AspNetUserClaims;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetUserLogins
     */
    var AspNetUserLogins = (function () {
        function AspNetUserLogins() {
            //nothing                   
        }
        return AspNetUserLogins;
    }());
    App.AspNetUserLogins = AspNetUserLogins;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetUserRoles
     */
    var AspNetUserRoles = (function () {
        function AspNetUserRoles() {
            //nothing                   
        }
        return AspNetUserRoles;
    }());
    App.AspNetUserRoles = AspNetUserRoles;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetUsers
     */
    var AspNetUsers = (function () {
        function AspNetUsers() {
            //nothing                   
        }
        return AspNetUsers;
    }());
    App.AspNetUsers = AspNetUsers;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetUserTokens
     */
    var AspNetUserTokens = (function () {
        function AspNetUserTokens() {
            //nothing                   
        }
        return AspNetUserTokens;
    }());
    App.AspNetUserTokens = AspNetUserTokens;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.BusinessType
     */
    var BusinessType = (function () {
        function BusinessType() {
            //nothing                   
        }
        return BusinessType;
    }());
    App.BusinessType = BusinessType;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.ChangePasswordViewModel
     */
    var ChangePasswordViewModel = (function () {
        function ChangePasswordViewModel() {
            //nothing                   
        }
        return ChangePasswordViewModel;
    }());
    App.ChangePasswordViewModel = ChangePasswordViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.ChartOfAccounts
     */
    var ChartOfAccounts = (function () {
        function ChartOfAccounts() {
            //nothing                   
        }
        return ChartOfAccounts;
    }());
    App.ChartOfAccounts = ChartOfAccounts;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Contactme
     */
    var Contactme = (function () {
        function Contactme() {
            //nothing                   
        }
        return Contactme;
    }());
    App.Contactme = Contactme;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.CreditCardTransactionInfo
     */
    var CreditCardTransactionInfo = (function () {
        function CreditCardTransactionInfo() {
            //nothing                   
        }
        return CreditCardTransactionInfo;
    }());
    App.CreditCardTransactionInfo = CreditCardTransactionInfo;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Creditnewcks
     */
    var Creditnewcks = (function () {
        function Creditnewcks() {
            //nothing                   
        }
        return Creditnewcks;
    }());
    App.Creditnewcks = Creditnewcks;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Credittypes
     */
    var Credittypes = (function () {
        function Credittypes() {
            //nothing                   
        }
        return Credittypes;
    }());
    App.Credittypes = Credittypes;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Departments
     */
    var Departments = (function () {
        function Departments() {
            //nothing                   
        }
        return Departments;
    }());
    App.Departments = Departments;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Emails
     */
    var Emails = (function () {
        function Emails() {
            //nothing                   
        }
        return Emails;
    }());
    App.Emails = Emails;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Emailstosend
     */
    var Emailstosend = (function () {
        function Emailstosend() {
            //nothing                   
        }
        return Emailstosend;
    }());
    App.Emailstosend = Emailstosend;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Employees
     */
    var Employees = (function () {
        function Employees() {
            //nothing                   
        }
        return Employees;
    }());
    App.Employees = Employees;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.EnableAuthenticatorViewModel
     */
    var EnableAuthenticatorViewModel = (function () {
        function EnableAuthenticatorViewModel() {
            //nothing                   
        }
        return EnableAuthenticatorViewModel;
    }());
    App.EnableAuthenticatorViewModel = EnableAuthenticatorViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.ErrorViewModel
     */
    var ErrorList = (function () {
        function ErrorList() {
            //nothing                   
        }
        return ErrorList;
    }());
    App.ErrorList = ErrorList;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.ErrorViewModel
     */
    var ErrorViewModel = (function () {
        function ErrorViewModel() {
            //nothing                   
        }
        return ErrorViewModel;
    }());
    App.ErrorViewModel = ErrorViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.ExternalLoginViewModel
     */
    var ExternalLoginViewModel = (function () {
        function ExternalLoginViewModel() {
            //nothing                   
        }
        return ExternalLoginViewModel;
    }());
    App.ExternalLoginViewModel = ExternalLoginViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.FacebookAppAccess
     */
    var FacebookAppAccess = (function () {
        function FacebookAppAccess() {
            //nothing                   
        }
        return FacebookAppAccess;
    }());
    App.FacebookAppAccess = FacebookAppAccess;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.FacebookOptions
     */
    var FacebookOptions = (function () {
        function FacebookOptions() {
            //nothing                   
        }
        return FacebookOptions;
    }());
    App.FacebookOptions = FacebookOptions;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Favs
     */
    var Favs = (function () {
        function Favs() {
            //nothing                   
        }
        return Favs;
    }());
    App.Favs = Favs;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.ForgotPasswordViewModel
     */
    var ForgotPasswordViewModel = (function () {
        function ForgotPasswordViewModel() {
            //nothing                   
        }
        return ForgotPasswordViewModel;
    }());
    App.ForgotPasswordViewModel = ForgotPasswordViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Forgotsent
     */
    var Forgotsent = (function () {
        function Forgotsent() {
            //nothing                   
        }
        return Forgotsent;
    }());
    App.Forgotsent = Forgotsent;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.GenerateRecoveryCodesViewModel
     */
    var GenerateRecoveryCodesViewModel = (function () {
        function GenerateRecoveryCodesViewModel() {
            //nothing                   
        }
        return GenerateRecoveryCodesViewModel;
    }());
    App.GenerateRecoveryCodesViewModel = GenerateRecoveryCodesViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.Geometry
     */
    var Geometry = (function () {
        function Geometry() {
            //nothing                   
        }
        return Geometry;
    }());
    App.Geometry = Geometry;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.GoogleApi
     */
    var GoogleApi = (function () {
        function GoogleApi() {
            //nothing                   
        }
        return GoogleApi;
    }());
    App.GoogleApi = GoogleApi;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.GooglePlaces
     */
    var GooglePlaces = (function () {
        function GooglePlaces() {
            //nothing                   
        }
        return GooglePlaces;
    }());
    App.GooglePlaces = GooglePlaces;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.IndexViewModel
     */
    var IndexViewModel = (function () {
        function IndexViewModel() {
            //nothing                   
        }
        return IndexViewModel;
    }());
    App.IndexViewModel = IndexViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Invites
     */
    var Invites = (function () {
        function Invites() {
            //nothing                   
        }
        return Invites;
    }());
    App.Invites = Invites;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.Location
     */
    var Location = (function () {
        function Location() {
            //nothing                   
        }
        return Location;
    }());
    App.Location = Location;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.LoginInputModel
     */
    var LoginInputModel = (function () {
        function LoginInputModel() {
            //nothing                   
        }
        return LoginInputModel;
    }());
    App.LoginInputModel = LoginInputModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.LoginViewModel
     */
    var LoginViewModel = (function () {
        function LoginViewModel() {
            //nothing                   
        }
        return LoginViewModel;
    }());
    App.LoginViewModel = LoginViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.LoginWith2faViewModel
     */
    var LoginWith2faViewModel = (function () {
        function LoginWith2faViewModel() {
            //nothing                   
        }
        return LoginWith2faViewModel;
    }());
    App.LoginWith2faViewModel = LoginWith2faViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.LoginWithRecoveryCodeViewModel
     */
    var LoginWithRecoveryCodeViewModel = (function () {
        function LoginWithRecoveryCodeViewModel() {
            //nothing                   
        }
        return LoginWithRecoveryCodeViewModel;
    }());
    App.LoginWithRecoveryCodeViewModel = LoginWithRecoveryCodeViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Masterbank
     */
    var Masterbank = (function () {
        function Masterbank() {
            //nothing                   
        }
        return Masterbank;
    }());
    App.Masterbank = Masterbank;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Masterlookup
     */
    var Masterlookup = (function () {
        function Masterlookup() {
            //nothing                   
        }
        return Masterlookup;
    }());
    App.Masterlookup = Masterlookup;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Msgsglobal
     */
    var Msgsglobal = (function () {
        function Msgsglobal() {
            //nothing                   
        }
        return Msgsglobal;
    }());
    App.Msgsglobal = Msgsglobal;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.Northeast
     */
    var Northeast = (function () {
        function Northeast() {
            //nothing                   
        }
        return Northeast;
    }());
    App.Northeast = Northeast;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.OpeningHours
     */
    var OpeningHours = (function () {
        function OpeningHours() {
            //nothing                   
        }
        return OpeningHours;
    }());
    App.OpeningHours = OpeningHours;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.Photo
     */
    var Photo = (function () {
        function Photo() {
            //nothing                   
        }
        return Photo;
    }());
    App.Photo = Photo;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Punchclock
     */
    var Punchclock = (function () {
        function Punchclock() {
            //nothing                   
        }
        return Punchclock;
    }());
    App.Punchclock = Punchclock;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.PushNotifications
     */
    var PushNotifications = (function () {
        function PushNotifications() {
            //nothing                   
        }
        return PushNotifications;
    }());
    App.PushNotifications = PushNotifications;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.RegisterViewModel
     */
    var RegisterViewModel = (function () {
        function RegisterViewModel() {
            //nothing                   
        }
        return RegisterViewModel;
    }());
    App.RegisterViewModel = RegisterViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.RemoveLoginViewModel
     */
    var RemoveLoginViewModel = (function () {
        function RemoveLoginViewModel() {
            //nothing                   
        }
        return RemoveLoginViewModel;
    }());
    App.RemoveLoginViewModel = RemoveLoginViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.ResetPasswordViewModel
     */
    var ResetPasswordViewModel = (function () {
        function ResetPasswordViewModel() {
            //nothing                   
        }
        return ResetPasswordViewModel;
    }());
    App.ResetPasswordViewModel = ResetPasswordViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.Result
     */
    var Result = (function () {
        function Result() {
            //nothing                   
        }
        return Result;
    }());
    App.Result = Result;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.RuntimeAds
     */
    var RuntimeAds = (function () {
        function RuntimeAds() {
            //nothing                   
        }
        return RuntimeAds;
    }());
    App.RuntimeAds = RuntimeAds;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.SetPasswordViewModel
     */
    var SetPasswordViewModel = (function () {
        function SetPasswordViewModel() {
            //nothing                   
        }
        return SetPasswordViewModel;
    }());
    App.SetPasswordViewModel = SetPasswordViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.SmsSettings
     */
    var SmsSettings = (function () {
        function SmsSettings() {
            //nothing                   
        }
        return SmsSettings;
    }());
    App.SmsSettings = SmsSettings;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.Southwest
     */
    var Southwest = (function () {
        function Southwest() {
            //nothing                   
        }
        return Southwest;
    }());
    App.Southwest = Southwest;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Taccounts
     */
    var Taccounts = (function () {
        function Taccounts() {
            //nothing                   
        }
        return Taccounts;
    }());
    App.Taccounts = Taccounts;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Tests
     */
    var Tests = (function () {
        function Tests() {
            //nothing                   
        }
        return Tests;
    }());
    App.Tests = Tests;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Testsqa
     */
    var Testsqa = (function () {
        function Testsqa() {
            //nothing                   
        }
        return Testsqa;
    }());
    App.Testsqa = Testsqa;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Tnews
     */
    var Tnews = (function () {
        function Tnews() {
            //nothing                   
        }
        return Tnews;
    }());
    App.Tnews = Tnews;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Tuuid
     */
    var Tuuid = (function () {
        function Tuuid() {
            //nothing                   
        }
        return Tuuid;
    }());
    App.Tuuid = Tuuid;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Tvideos
     */
    var Tvideos = (function () {
        function Tvideos() {
            //nothing                   
        }
        return Tvideos;
    }());
    App.Tvideos = Tvideos;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.TwoFactorAuthenticationViewModel
     */
    var TwoFactorAuthenticationViewModel = (function () {
        function TwoFactorAuthenticationViewModel() {
            //nothing                   
        }
        return TwoFactorAuthenticationViewModel;
    }());
    App.TwoFactorAuthenticationViewModel = TwoFactorAuthenticationViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.UserInfoViewModel
     */
    var UserInfoViewModel = (function () {
        function UserInfoViewModel() {
            //nothing                   
        }
        return UserInfoViewModel;
    }());
    App.UserInfoViewModel = UserInfoViewModel;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Web.Models.Viewport
     */
    var Viewport = (function () {
        function Viewport() {
            //nothing                   
        }
        return Viewport;
    }());
    App.Viewport = Viewport;
})(App || (App = {}));
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
(function (App) {
    /**
     * Base view model for OrderGrabGo.Dll.Models.Ziplist
     */
    var Ziplist = (function () {
        function Ziplist() {
            //nothing                   
        }
        return Ziplist;
    }());
    App.Ziplist = Ziplist;
})(App || (App = {}));
//# sourceMappingURL=models.js.map