//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Ads
     */
    export class Ads    {
         
        Id: number;
        PageName: string;
        Action: string;
        BuyerId: number;
        AdTitle: string;
        AdDescription: string;
        SiteId: number;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetRoleClaims
     */
    export class AspNetRoleClaims    {
         
        Id: number;
        ClaimType: string;
        ClaimValue: string;
        RoleId: string;
        Role: AspNetRoles;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetRoles
     */
    export class AspNetRoles    {
         
        Id: string;
        ConcurrencyStamp: string;
        Name: string;
        NormalizedName: string;
        AspNetRoleClaims: AspNetRoleClaims[];
        AspNetUserRoles: AspNetUserRoles[];  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetUserClaims
     */
    export class AspNetUserClaims    {
         
        Id: number;
        ClaimType: string;
        ClaimValue: string;
        UserId: string;
        User: AspNetUsers;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetUserLogins
     */
    export class AspNetUserLogins    {
         
        LoginProvider: string;
        ProviderKey: string;
        ProviderDisplayName: string;
        UserId: string;
        User: AspNetUsers;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetUserRoles
     */
    export class AspNetUserRoles    {
         
        UserId: string;
        RoleId: string;
        Role: AspNetRoles;
        User: AspNetUsers;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetUsers
     */
    export class AspNetUsers    {
         
        Id: string;
        AccessFailedCount: number;
        ConcurrencyStamp: string;
        Email: string;
        EmailConfirmed: boolean;
        LockoutEnabled: boolean;
        LockoutEnd: Date;
        NormalizedEmail: string;
        NormalizedUserName: string;
        PasswordHash: string;
        PhoneNumber: string;
        PhoneNumberConfirmed: boolean;
        SecurityStamp: string;
        TwoFactorEnabled: boolean;
        UserName: string;
        AspNetUserClaims: AspNetUserClaims[];
        AspNetUserLogins: AspNetUserLogins[];
        AspNetUserRoles: AspNetUserRoles[];  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.AspNetUserTokens
     */
    export class AspNetUserTokens    {
         
        UserId: string;
        LoginProvider: string;
        Name: string;
        Value: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.BusinessType
     */
    export class BusinessType    {
         
        Id: number;
        Typedesc: string;
        Category: number;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.ChangePasswordViewModel
     */
    export class ChangePasswordViewModel    {
         
        OldPassword: string;
        NewPassword: string;
        ConfirmPassword: string;
        StatusMessage: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.ChartOfAccounts
     */
    export class ChartOfAccounts    {
         
        Id: number;
        Account: number;
        Term: string;
        Department: string;
        Definition: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Contactme
     */
    export class Contactme    {
         
        Id: number;
        Low: number;
        LoginId: number;
        BuyerId: number;
        SellerId: number;
        FirstName: string;
        LastName: string;
        CellPhone: string;
        ZipCode: number;
        StreetNum: number;
        StreetAddress: string;
        Company: string;
        Email: string;
        Message: string;
        PreferredContact: number;
        UniqueId: number;
        ContactedByEmpId: number;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.CreditCardTransactionInfo
     */
    export class CreditCardTransactionInfo    {
         
        Id: number;
        InternetProtocol: string;
        BuyerId: number;
        SellerId: number;
        BoothId: number;
        OrderId: number;
        Amount: number;
        Tax: number;
        Zip: number;
        CreditCard: string;
        NameOnCard: string;
        Ccexpyear: string;
        Ccexpmonth: string;
        PaidWith: string;
        RApproved: string;
        RTime: string;
        RError: string;
        ROrdernumber: string;
        RCode: string;
        Ncresponse: string;
        Test: number;
        CashBak: number;
        Purchase: number;
        Email: string;
        Description: string;
        Cvv: string;
        Addrnum: number;
        Configfile: string;
        Ordertype: string;
        Chargetotal: number;
        RCsp: string;
        RRef: string;
        RMessage: string;
        RTdate: string;
        RScore: string;
        RAuthresponse: string;
        RAvs: string;
        Gender: string;
        Company: string;
        FirstName: string;
        LastName: string;
        MiddleName: string;
        Address1: string;
        Address2: string;
        City: string;
        State: string;
        HomePhone: string;
        WorkPhone: string;
        CellPhone: string;
        DrivingLicense: string;
        DrivingState: string;
        Dlexpire: string;
        Ssn: string;
        Dob: Date;
        Country: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Creditnewcks
     */
    export class Creditnewcks    {
         
        Id: number;
        Uuid: string;
        Ip: string;
        MasterLookUpId: number;
        OperatingSystemId: number;
        StatusId: number;
        WhoEnteredCid: number;
        BankId: number;
        CreditType: string;
        AcctNum: string;
        NameOnCard: string;
        Cvv: string;
        ExpDate: string;
        Zip: string;
        CreditLimit: number;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Credittypes
     */
    export class Credittypes    {
         
        Id: number;
        CreditType: string;
        Description: string;
        Brand: number;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Departments
     */
    export class Departments    {
         
        Id: number;
        Name: string;
        SubDepartmentId: number;
        Description: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Emails
     */
    export class Emails    {
         
        Id: number;
        LoginId: number;
        Email: string;
        BlockedEmails: number;
        BadEmailAddress: number;
        Ip: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Emailstosend
     */
    export class Emailstosend    {
         
        Id: number;
        Page: string;
        SiteId: number;
        BadEmailId: number;
        DepartId: number;
        MasterLookupId: number;
        EnteredByMlid: number;
        EmpId: number;
        FirstName: string;
        LastName: string;
        Email: string;
        State: string;
        Zip: number;
        CellPhone: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Employees
     */
    export class Employees    {
         
        EmployeeId: number;
        MasterLookUpId: number;
        SquareId: string;
        UpLineMasterLookUpId: number;
        SuperVisorEid: number;
        EmployerId: number;
        EmpTypeId: number;
        PassWord: string;
        ContractDate: string;
        ClosedOut: string;
        Discount: number;
        SubContractor: number;
        AccessLevel: number;
        DepartmentId: number;
        StartDate: string;
        DepositInfo: string;
        ReportArea: number;
        SellArea: number;
        CanBuy: number;
        BuyLimit: number;
        BioData: string;
        Active: number;
        LockOut: number;
        Extension: string;
        Exempt: number;
        Department: number;
        HourlyRate: number;
        RateCommission: number;
        Salary: number;
        CurrentDrawAmount: number;
        HourlyRateOrSalary: number;
        EmergContact: string;
        EmergPhone: string;
        HospitalDoctor: string;
        Title: string;
        Notes: string;
        ReportsTo: number;
        Disabled: number;
        Veteren: number;
        DeductableInsurance: number;
        Deductable1: number;
        Deductable2: number;
        Deductable3: number;
        MonB: string;
        MonE: string;
        TueB: string;
        TueE: string;
        WedB: string;
        WedE: string;
        ThuB: string;
        ThuE: string;
        FriB: string;
        FriE: string;
        SatB: string;
        SatE: string;
        SunB: string;
        SunE: string;
        PayDay: string;
        FirstPayDay: number;
        SecPayDay: number;
        SignedNdadate: string;
        Mon: string;
        Tue: string;
        Wed: string;
        Thu: string;
        Fri: string;
        Sat: string;
        Sun: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.EnableAuthenticatorViewModel
     */
    export class EnableAuthenticatorViewModel    {
         
        Code: string;
        SharedKey: string;
        AuthenticatorUri: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}
//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.ErrorViewModel
     */
    export class ErrorList    {
         
        Error: string;
  token: string;
        IsSuccess: boolean;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.ErrorViewModel
     */
    export class ErrorViewModel    {
         
        RequestId: string;
        ShowRequestId: boolean;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.ExternalLoginViewModel
     */
    export class ExternalLoginViewModel    {
         
        Email: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.FacebookAppAccess
     */
    export class FacebookAppAccess    {
         
        access_token: string;
        token_type: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.FacebookOptions
     */
    export class FacebookOptions    {
         
        ApiUrl: string;
        AppId: string;
        AppSecret: string;
        AppTokenUrl: string;
        DebugUrl: string;
        PicUrl: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Favs
     */
    export class Favs    {
         
        Id: number;
        BuyerId: number;
        UniqueId: number;
        SellerId: number;
        SortBy: number;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.ForgotPasswordViewModel
     */
    export class ForgotPasswordViewModel    {
         
        Email: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Forgotsent
     */
    export class Forgotsent    {
         
        Id: number;
        Page: string;
        SiteId: number;
        InternetProtocol: string;
        DepartId: number;
        MasterLookUpId: number;
        EnteredByMlid: number;
        EmpId: number;
        FirstName: string;
        LastName: string;
        Email: string;
        State: string;
        Zip: number;
        Phone: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.GenerateRecoveryCodesViewModel
     */
    export class GenerateRecoveryCodesViewModel    {
         
        RecoveryCodes: string[];  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.Geometry
     */
    export class Geometry    {
         
        location: Location;
        viewport: Viewport;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.GoogleApi
     */
    export class GoogleApi    {
         
        NearByPlacesUrl: string;
        ApiKey: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.GooglePlaces
     */
    export class GooglePlaces    {
         
        html_attributions: any[];
        next_page_token: string;
        results: Result[];
        status: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.IndexViewModel
     */
    export class IndexViewModel    {
         
        Username: string;
        IsEmailConfirmed: boolean;
        Email: string;
        PhoneNumber: string;
        StatusMessage: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Invites
     */
    export class Invites    {
         
        Id: number;
        Ip: string;
        InvitedToRestId: number;
        Donated: number;
        SentMlid: number;
        RecMlid: number;
        SentToEmail: string;
        DateRespond: Date;
        StatusId: number;
        RecOrderId: number;
        SenderOrderId: number;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.Location
     */
    export class Location    {
         
        lat: number;
        lng: number;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.LoginInputModel
     */
    export class LoginInputModel    {
         
        Username: string;
        Password: string;
        RememberLogin: boolean;
        ReturnUrl: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.LoginViewModel
     */
    export class LoginViewModel    {
         
        Email: string;
        Password: string;
        RememberMe: boolean;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.LoginWith2faViewModel
     */
    export class LoginWith2faViewModel    {
         
        TwoFactorCode: string;
        RememberMachine: boolean;
        RememberMe: boolean;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.LoginWithRecoveryCodeViewModel
     */
    export class LoginWithRecoveryCodeViewModel    {
         
        RecoveryCode: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Masterbank
     */
    export class Masterbank    {
         
        Id: number;
        RoutingNum: string;
        BankName: string;
        BankCity: string;
        BankState: string;
        BankZip: string;
        BankPhone: string;
        BankFax: string;
        DeptForAcctNums: string;
        Contact: string;
        BankCountry: string;
        Verified: string;
        EditDate: Date;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Masterlookup
     */
    export class Masterlookup    {
         
        UserId: number;
        IsApp: number;
        InstantCash: number;
        FreeMeal: number;
        SellerId: number;
        SiteId: number;
        Referid: number;
        InsertCid: number;
        Video: number;
        GiveChance: number;
        OwnerId: number;
        Frozen: number;
        UserName: string;
        Password: string;
        PurchaseId: number;
        TeamSize: number;
        SubContract: number;
        Www: string;
        Company: string;
        Gender: string;
        FirstName: string;
        Initial: string;
        LastName: string;
        Half: string;
        StreetNum: number;
        Street: string;
        Apt: string;
        City: string;
        State: string;
        Zip: string;
        WorkPhone: string;
        CellPhone: string;
        Ext: string;
        Marital: string;
        Dob: Date;
        AptDate: Date;
        LineOfWork: number;
        HasPhoto: number;
        BadAddress: number;
        Ssn: string;
        Dl: string;
        Dlst: string;
        Dlexp: string;
        Points: number;
        EmailsOk: number;
        TxtMsgOk: number;
        UserType: string;
        OfferId: number;
        WeStoppedAcct: number;
        OwnerStoppedAcct: number;
        Email: string;
        EmailChgPass: number;
        Virus: number;
        Verified: number;
        AdultLev: number;
        SpamLev: number;
        StorageGb: number;
        StorageDays: number;
        WantsGenie: number;
        EmailOnly: number;
        Unqid: number;
        Sic: number;
        AllowsTours: number;
        LoginId: number;
        Title: string;
        Lon: number;
        Lat: number;
        CurrLon: number;
        CurrLat: number;
        CarLon: number;
        CarLat: number;
        ReadyToWork: number;
        EditDate: Date;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Msgsglobal
     */
    export class Msgsglobal    {
         
        MsgId: number;
        Msg: string;
        Internal: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.Northeast
     */
    export class Northeast    {
         
        lat: number;
        lng: number;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.OpeningHours
     */
    export class OpeningHours    {
         
        open_now: boolean;
        weekday_text: any[];  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.Photo
     */
    export class Photo    {
         
        height: number;
        html_attributions: string[];
        photo_reference: string;
        width: number;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Punchclock
     */
    export class Punchclock    {
         
        Id: number;
        Empid: number;
        Ip: string;
        PayStubsId: number;
        Punchin: Date;
        Punchout: Date;
        Hrs: number;
        Mins: number;
        Lunch: number;
        JobId: number;
        Tips: number;
        Note: string;
        WhoInputId: number;
        EmpNote: string;
        CreateDate: number[];  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.PushNotifications
     */
    export class PushNotifications    {
         
        Token: string;
        AppId: string;
        ApiKey: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.RegisterViewModel
     */
    export class RegisterViewModel    {
         
        Email: string;
        Password: string;
        ConfirmPassword: string;
        PhoneNumber: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.RemoveLoginViewModel
     */
    export class RemoveLoginViewModel    {
         
        LoginProvider: string;
        ProviderKey: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.AccountViewModels.ResetPasswordViewModel
     */
    export class ResetPasswordViewModel    {
         
        Email: string;
        Password: string;
        ConfirmPassword: string;
        Code: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.Result
     */
    export class Result    {
         
        formatted_address: string;
        geometry: Geometry;
        icon: string;
        id: string;
        name: string;
        opening_hours: OpeningHours;
        photos: Photo[];
        place_id: string;
        price_level: number;
        rating: number;
        reference: string;
        types: string[];  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.RuntimeAds
     */
    export class RuntimeAds    {
         
        Id: number;
        BuyerId: number;
        RunDate: Date;
        Vendor: string;
        VenderId: number;
        Cost: number;
        Headline: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.SetPasswordViewModel
     */
    export class SetPasswordViewModel    {
         
        NewPassword: string;
        ConfirmPassword: string;
        StatusMessage: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.SmsSettings
     */
    export class SmsSettings    {
         
        Sid: string;
        Token: string;
        BaseUri: string;
        RequestUri: string;
        From: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.Southwest
     */
    export class Southwest    {
         
        lat: number;
        lng: number;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Taccounts
     */
    export class Taccounts    {
         
        Id: number;
        MasterLookId: number;
        IsBiz: number;
        BankId: number;
        Nick: string;
        CreditType: string;
        AcctNum: string;
        NameOnCard: string;
        Cvv: string;
        ExpDate: string;
        Zip: string;
        CreditLimit: number;
        WhoEnteredCid: number;
        StatusId: number;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Tests
     */
    export class Tests    {
         
        Id: number;
        ALevList: string;
        DepartList: string;
        InputCid: number;
        Bid: number;
        Approx: number;
        Name: string;
        MotivationalSubHeading: string;
        Mission: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Testsqa
     */
    export class Testsqa    {
         
        Id: number;
        TestId: number;
        Question: number;
        Answer: string;
        QuestionBody: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Tnews
     */
    export class Tnews    {
         
        Id: number;
        SellerId: number;
        Title: string;
        Msg: string;
        Lon: number;
        Lat: number;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Tuuid
     */
    export class Tuuid    {
         
        Id: number;
        MasterLookupId: number;
        GlobalRefreshTime: Date;
        Phone: string;
        Osid: number;
        UniqueId: string;
        Token: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Tvideos
     */
    export class Tvideos    {
         
        Id: number;
        Importance: number;
        Type: number;
        Name: string;
        Link: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.ManageViewModels.TwoFactorAuthenticationViewModel
     */
    export class TwoFactorAuthenticationViewModel    {
         
        HasAuthenticator: boolean;
        RecoveryCodesLeft: number;
        Is2faEnabled: boolean;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.UserInfoViewModel
     */
    export class UserInfoViewModel    {
         
        FirstName: string;
        LastName: string;
        DateOfBirth: Date;
        ZipCode: string;
        UserId: string;
        Email: string;
        Picture: string;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Web.Models.Viewport
     */
    export class Viewport    {
         
        northeast: Northeast;
        southwest: Southwest;  
 
        constructor() {         
          //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 
export module App {
     
   
    /**
     * Base view model for OrderGrabGo.Dll.Models.Ziplist
     */
    export class Ziplist    {
         
        Id: number;
        Zip: string;
        ZipcodeType: string;
        City: string;
        CityType: string;
        County: string;
        CountyFips: string;
        State: string;
        St: string;
        StateFips: string;
        Msa: string;
        Ac: string;
        TimeZone: string;
        Gmtoffset: number;
        Dst: string;
        Latitude: number;
        Longitude: number;
        Country: string;
        CreateDate: Date;  
 
        constructor() {         
          //nothing                   
        }
    }
}

export module App {
    export class ProductMenu {
        ProductMaster: any;
    }
}

export module App {
    export class Takeout {
        FirstName: string;
        LastName: string;
        PhoneNumber: string;
        Email: string;
        PickupDate: string;
        PickupTime: string;
        Location: string;
    }
}

//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.CustomerMaster
     */
    export class CustomerMaster {

        CustomerId: number;
        Address: string;
        CreatedDate: Date;
        CreatedUserId: string;
        DateOfBirth: Date;
        Email: string;
        FirstName: string;
        GeoLocation: string;
        IsActive: boolean;
        IsDeleted: boolean;
        LastName: string;
        LookupCityId: number;
        City: string;
        LookupCountryId: number;
        LookupLocalityId: number;
        LookupStateId: number;
        MobileNumber: number;
        ModifiedDate: Date;
        ModifiedUserId: string;
        UserId: string;
        LookupCity: LookupCodeMaster;
        LookupCountry: LookupCodeMaster;
        LookupLocality: LookupCodeMaster;
        LookupState: LookupCodeMaster;
        User: AspNetUsers;
        Orders: Orders[];

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.LookupCodeMaster
     */
    export class LookupCodeMaster {

        LookupCodeId: number;
        CreatedDate: Date;
        CreatedUserId: string;
        IsActive: boolean;
        IsDeleted: boolean;
        LookupCode: string;
        LookupCodeName: string;
        LookupTypeId: number;
        ModifiedDate: Date;
        ModifiedUserId: string;
        LookupType: LookupTypeMaster;
        CustomerMasterLookupCity: CustomerMaster[];
        CustomerMasterLookupCountry: CustomerMaster[];
        CustomerMasterLookupLocality: CustomerMaster[];
        CustomerMasterLookupState: CustomerMaster[];
        Orders: Orders[];
        ProductMaster: ProductMaster[];
        RestaurantContactMasterLookupCity: RestaurantContactMaster[];
        RestaurantContactMasterLookupCountry: RestaurantContactMaster[];
        RestaurantContactMasterLookupLocality: RestaurantContactMaster[];
        RestaurantContactMasterLookupState: RestaurantContactMaster[];
        RestaurantMasterLookupCity: RestaurantMaster[];
        RestaurantMasterLookupCountry: RestaurantMaster[];
        RestaurantMasterLookupLocality: RestaurantMaster[];
        RestaurantMasterLookupState: RestaurantMaster[];
        RestaurantModules: RestaurantModules[];
        RestaurantTime: RestaurantTime[];

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.LookupTypeMaster
     */
    export class LookupTypeMaster {

        LookupTypeId: number;
        CreatedDate: Date;
        CreatedUserId: string;
        IsActive: boolean;
        IsDeleted: boolean;
        LookupCode: string;
        LookupTypeName: string;
        ModifiedDate: Date;
        ModifiedUserId: string;
        LookupCodeMaster: LookupCodeMaster[];

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Dll.OrderGrabGo_Models.MerchantContactMaster
     */
    export class MerchantContactMaster {

        MerchantContactId: number;
        MerchantId: number;
        IsPrimary: boolean;
        UserId: string;
        Address: string;
        LookupLocalityId: number;
        LookupCityId: number;
        LookupStateId: number;
        LookupCountryId: number;
        MobileNumber1: number;
        MobileNumber2: number;
        LandLineNumber1: number;
        LandLineNumber2: number;
        Email: string;
        GeoLocation: string;
        Website: string;
        CreatedUserId: number;
        CreatedDate: Date;
        ModifiedUserId: number;
        ModifiedDate: Date;
        IsActive: boolean;
        IsDeleted: boolean;
        LookupCity: LookupCodeMaster;
        LookupCountry: LookupCodeMaster;
        LookupState: LookupCodeMaster;
        Merchant: MerchantMaster;
        MerchantContact: LookupCodeMaster;

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Dll.OrderGrabGo_Models.MerchantMaster
     */
    export class MerchantMaster {

        MerchantId: number;
        MerchantName: string;
        CreatedUserId: number;
        CreatedDate: Date;
        ModifiedUserId: number;
        ModifiedDateId: Date;
        IsActive: boolean;
        IsDeleted: boolean;
        MerchantContactMaster: MerchantContactMaster[];

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.OrderDetail
     */
    export class OrderDetail {

        OrderDetailId: number;
        CreatedDate: Date;
        CreatedUserId: string;
        IsActive: boolean;
        IsDeleted: boolean;
        ModifiedDate: Date;
        ModifiedUserId: string;
        OrderId: number;
        Price: number;
        ProductId: number;
        Quantity: number;
        Order: Orders;
        Product: ProductMaster;

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************



//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.Orders
     */
    export class Orders {

        OrderId: number;
        CompletionDate: Date;
        CreatedDate: Date;
        CreatedUserId: string;
        CustomerId: number;
        Instructions: string;
        IsActive: boolean;
        IsDeleted: boolean;
        LookupOrderTypeId: number;
        LookupStatusId: number;
        ModifiedDate: Date;
        ModifiedUserId: string;
        OrderTotal: number;
        ResturantId: number;
        Customer: CustomerMaster;
        CustomerMaster: CustomerMaster;
        LookupStatus: LookupCodeMaster;
        Resturant: RestaurantMaster;
        OrderDetail: OrderDetail[];

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.ProductMaster
     */
    export class ProductMaster {

        ProductId: number;
        CreatedDate: Date;
        CreatedUserId: string;
        ImagePath: string;
        IsActive: boolean;
        IsDeleted: boolean;
        LookupCuisineId: number;
        ModifiedDate: Date;
        ModifiedUserId: string;
        Price: number;
        ProductCode: string;
        ProductDescription: string;
        ProductName: string;
        RestaurantId: number;
        LookupCuisine: LookupCodeMaster;
        Restaurant: RestaurantMaster;
        SubProductType: SubProductType;
        OrderDetail: OrderDetail[];

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Dll.OrderGrabGo_Models.PushTokens
     */
    export class PushTokens {

        UserId: string;
        PushToken: string;
        isActive: boolean;

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.RestaurantBanquet
     */
    export class RestaurantBanquet {

        BanquetId: number;
        BanquetDescription: string;
        CreatedDate: Date;
        CreatedUserId: string;
        IsActive: boolean;
        IsDeleted: boolean;
        MinimumNoPeople: number;
        ModifiedDate: Date;
        ModifiedUserId: string;
        Name: string;
        RestaurantId: number;
        Restaurant: RestaurantMaster;

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.RestaurantCatering
     */
    export class RestaurantCatering {

        CateringId: number;
        CreatedDate: Date;
        CreatedUserId: string;
        Description: string;
        IsActive: boolean;
        IsDeleted: boolean;
        MinimumNoPeople: number;
        ModifiedDate: Date;
        ModifiedUserId: string;
        Name: string;
        RestaurantId: number;
        Restaurant: RestaurantMaster;

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.RestaurantContactMaster
     */
    export class RestaurantContactMaster {

        RestaurantContactId: number;
        Address: string;
        CreatedDate: Date;
        CreatedUserId: string;
        Email: string;
        GeoLocation: string;
        IsActive: number;
        IsDeleted: number;
        IsPrimary: boolean;
        LandLineNumber1: number;
        LandLineNumber2: number;
        LookupCityId: number;
        LookupCountryId: number;
        LookupLocalityId: number;
        LookupStateId: number;
        MobileNumber1: number;
        MobileNumber2: number;
        ModifiedDate: Date;
        ModifiedUserId: number;
        RestaurantId: number;
        UserId: string;
        VideoUrl: string;
        Website: string;
        LookupCity: LookupCodeMaster;
        LookupCountry: LookupCodeMaster;
        LookupLocality: LookupCodeMaster;
        LookupState: LookupCodeMaster;
        Restaurant: RestaurantMaster;
        User: AspNetUsers;

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.RestaurantMaster
     */
    export class RestaurantMaster {

        RestaurantId: number;
        Address: string;
        CreatedDate: Date;
        CreatedUserId: string;
        DeliveryFee: number;
        DeliveryMinCost: number;
        Email: string;
        EstDeliveryTime: number;
        GeoLocation: string;
        IsActive: boolean;
        IsDeleted: boolean;
        LandlineNumber1: number;
        LandlineNumber2: number;
        LookupCityId: number;
        LookupCountryId: number;
        LookupLocalityId: number;
        LookupStateId: number;
        MerchantId: number;
        MobileNumber1: number;
        MobileNumber2: number;
        ModifiedDate: Date;
        ModifiedUserId: string;
        RestaurantName: string;
        TakeOutEstimationTime: number;
        LookupCity: LookupCodeMaster;
        LookupCountry: LookupCodeMaster;
        LookupLocality: LookupCodeMaster;
        LookupState: LookupCodeMaster;
        Orders: Orders[];
        ProductMaster: ProductMaster[];
        RestaurantBanquet: RestaurantBanquet[];
        RestaurantCatering: RestaurantCatering[];
        RestaurantContactMaster: RestaurantContactMaster[];
        RestaurantModules: RestaurantModules[];
        RestaurantTime: RestaurantTime[];

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.RestaurantModules
     */
    export class RestaurantModules {

        ModuleId: number;
        CreatedDate: Date;
        CreatedUserId: string;
        IsActive: boolean;
        IsDeleted: boolean;
        LookupModuleId: number;
        ModifiedDate: Date;
        ModifiedUserId: string;
        RestaurantId: number;
        LookupModule: LookupCodeMaster;
        Restaurant: RestaurantMaster;

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.RestaurantTime
     */
    export class RestaurantTime {

        TimmingId: number;
        CloseTime: string;
        CreatedDate: Date;
        CreatedUserId: string;
        IsActive: boolean;
        IsDeleted: boolean;
        LookupDayId: number;
        ModifiedDate: Date;
        ModifiedUserId: string;
        OpenTime: string;
        RestaurantId: number;
        LookupDay: LookupCodeMaster;
        Restaurant: RestaurantMaster;

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.SubProductType
     */
    export class SubProductType {

        SubProductTypeId: number;
        CreatedDate: Date;
        CreatedUserId: string;
        IsActive: boolean;
        IsDeleted: boolean;
        ModifiedDate: Date;
        ModifiedUserId: string;
        ProductId: number;
        SubProductTypeCode: string;
        SubProductTypeName: string;
        SubProductTypePrice: number;
        SubProductTypeNavigation: ProductMaster;

        constructor() {
            //nothing                   
        }
    }
}




//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

export module App {


    /**
     * Base view model for OrderGrabGo.Web.OrderGrabGo_Models.UserProfile
     */
    export class UserProfile {

        Id: number;
        FirstName: string;
        LastName: string;
        DateOfBirth: Date;
        ZipCode: string;
        UserId: string;
        Picture: string;

        constructor() {
            //nothing                   
        }
    }
}